language: python

os:
  - linux

python:
  - 2.7
  - 3.6

addons:
  apt:
    packages:
      - python-numpy
      - python-setuptools

install:
  - pip install --upgrade pip
  - pip install -r requirements-travis.txt

env:
  - TEST_DIR=.;  TEST_SCRIPT="python setup.py test"

script: cd $TEST_DIR  &&  $TEST_SCRIPT && cd ..
