language: python

sudo: required

os:
  - linux

#python:
#  - 2.7
#  - 3.6

matrix:
  include:
    - env: MPI_LIBRARY=openmpi MPI_LIBRARY_VERSION=2.0.0
      python: 2.7
    - env: MPI_LIBRARY=openmpi MPI_LIBRARY_VERSION=2.0.0
      python: 3.6

addons:
  apt:
    packages:
      - python-numpy
      - python-setuptools

install:
  - sh install-mpi.sh
  - export MPI_PREFIX="${HOME}/opt/${MPI_LIBRARY}-${MPI_LIBRARY_VERSION}"
  - export PATH="${HOME}/.local/bin:${MPI_PREFIX}/bin${PATH:+":${PATH}"}"
  - export LD_LIBRARY_PATH="${MPI_PREFIX}/lib${LD_LIBRARY_PATH:+":${LD_LIBRARY_PATH}"}"
  - pip install --upgrade pip
  - pip install -r requirements-travis.txt

env:
  - TEST_DIR=.;  TEST_SCRIPT="python setup.py test"

script: cd $TEST_DIR  &&  $TEST_SCRIPT && cd ..
